/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.complexity;

import java.util.Arrays;
import java.util.Random;

public class App {
    public static void main(String[] args) throws Exception {
        // bigger the algorithm
        // more time and space it will consume

        int size = 10000000;
        int[] array = generateArray(10000000);
        shuffle(array);

        printHeader(size);

        int value = 100544;

        // ----------------------------------------
        // O(n)
        // ----------------------------------------

        new SearchExecutor(new LinearSearch()).search(value, array);

        // ----------------------------------------
        // O(log n)
        // ----------------------------------------

        // The key aspect here is that the array is already sorted
        int[] clonedArray = array.clone();
        Arrays.sort(clonedArray);
        // binary search keeps splitting the the search in 2 (left and right)
        new SearchExecutor(new BinarySearch()).search(value, clonedArray);
    }

    private static void printHeader(int size) {
        System.out.println("\n" +
                " ______________     _             _,-----------._        ___\n" +
                "|              |   (_,.-      _,-'_,-----------._`-._    _)_)\n" +
                "| THE _  _  _  |      |     ,'_,-'  ___________  `-._`.\n" +
                "| |  / \\|_)| \\ |     `'   ,','  _,-'___________`-._  `.`.\n" +
                "| |__\\_/| \\|_/ |        ,','  ,'_,-'     .     `-._`.  `.`.\n" +
                "|              |       /,'  ,','        >|<        `.`.  `.\\\n" +
                "| OF THE  _ _  |      //  ,','      ><  ,^.  ><      `.`.  \\\\\n" +
                "| |_)||\\|/_(_  |     //  /,'      ><   / | \\   ><      `.\\  \\\\\n" +
                "| | \\|| |\\_|_) |    //  //      ><    \\/\\^/\\/    ><      \\\\  \\\\\n" +
                "|______________|   ;;  ;;              `---'              ::  ::\n" +
                "                   ||  ||              (____              ||  ||\n" +
                " DOORS OF DURIN   _||__||_            ,'----.            _||__||_\n" +
                "                 (o.____.o)____        `---'        ____(o.____.o)\n" +
                "                   |    | /,--.)                   (,--.\\ |    |\n" +
                "                   |    |((  -`___               ___`   ))|    |\n" +
                "                   |    | \\\\,'',  `.           .'  .``.// |    |\n" +
                "                   |    |  // (___,'.         .'.___) \\\\  |    |\n" +
                "                  /|    | ;;))  ____) .     . (____  ((\\\\ |    |\\\n" +
                "                  \\|.__ | ||/ .'.--.\\/       `/,--.`. \\;: | __,|;\n" +
                "                   |`-,`;.| :/ /,'  `)-'   `-('  `.\\ \\: |.;',-'|\n" +
                "                   |   `..  ' / \\__.'         `.__/ \\ `  ,.'   |\n" +
                "                   |    |,\\  /,                     ,\\  /,|    |\n" +
                "                   |    ||: : )          .          ( : :||    |\n" +
                "                  /|    |:; |/  .      ./|\\,      ,  \\| :;|    |\\\n" +
                "                  \\|.__ |/  :  ,/-    <--:-->    ,\\.  ;  \\| __,|;\n" +
                "                   |`-.``:   `'/-.     '\\|/`     ,-\\`;   ;'',-'|\n" +
                "                   |   `..   ,' `'       '       `  `.   ,.'   |\n" +
                "                   |    ||  :                         :  ||    |\n" +
                "                   |    ||  |                         |  ||    |\n" +
                "                   |    ||  |                         |  ||    |\n" +
                "                   |    |'  |            _            |  `|    |\n" +
                "                   |    |   |          '|))           |   |    |\n" +
                "                   ;____:   `._        `'           _,'   ;____:\n" +
                "                  {______}     \\___________________/     {______}\n" +
                "              SSt |______|_______________________________|______|");

        System.out.println("\n\nUsing sample with " + size + " positions.");
        System.out.println("Running algorithms...");
    }

    private static void shuffle(int[] array) {
        final Random random = new Random();
        for (int i = 0; i < array.length; i++) {
            int index = random.nextInt(i + 1);
            int v = array[index];
            array[index] = array[i];
            array[i] = v;
        }
    }

    private static int[] generateArray(int size) {
        int[] array = new int[size];
        for (int i = 0; i < array.length; i++) {
            array[i] = i+1;
        }
        return array;
    }
}
